### ISSUE TITLE
BraTS2018-tumor-segmentation repo link

### ISSUE THREAD

**Issue by akhanss** [pykao/Modified-3D-UNet-Pytorch#2]
Hi @pykao 
Thanks for great repo. I am just wondering if you can provide proper link for BraTS2018-tumor-segmentation as you mentioned at the end of the README.md-

Please refer to our [BraTS2018-tumor-segmentation repo](https://github.com/pykao/BraTS2018-tumor-segmentation) if you would like to use this model on brain tumor segmentation.

Best,
Azam.

**Comment by pykao** [comment]
Dear Azam,

We decided not to make this repo public at this time. But you are able to use our proposed ensemble from our [Docker repo](https://hub.docker.com/r/pykao/brats2018/). 

Our [paper](https://www.researchgate.net/publication/326549702_Brain_Tumor_Segmentation_and_Tractographic_Feature_Extraction_from_Structural_MR_Images_for_Overall_Survival_Prediction/comments) explains more details on the architecture of our ensemble.

Best, 
Po-Yu Kao
