### ISSUE TITLE
 training part and data loading part

### ISSUE THREAD

**Issue by JunMa11** [pykao/Modified-3D-UNet-Pytorch#4]
Thanks for the great respo.
I'm really enjoying your work, but I'm a starter in pytorch. 
Would it be possible for you to release the training part and data loading part? So this project can be used to training models based on local data.

Looking forward to your reply.
Edward

**Comment by pykao** [comment]
Thank for your interesting. I am working on another repo and the new repo will be released soon.

**Comment by JunMa11** [comment]
Hi @pykao , I'm looking forward to the new repo.
If you need some code testing, I will be happy to do it.

**Comment by pykao** [comment]
Sure, I will let you know once we make the repo public.
