### ISSUE TITLE
input shape of the modified unet 

### ISSUE THREAD

**Issue by DecentMakeover** [pykao/Modified-3D-UNet-Pytorch#5]
Hi 

Thanks for sharing your work, 

Does the modified unet expect a fixed shape like (1,1,128,128,128) or will any shape do ?

Thanks in advance.

**Comment by dscarmo** [comment]
Look at the number of max pools performed by the Net, each one will divide shape[2:] by 2. 
Since its a fully convolutional network, if you never get to a 1, 1, 1, 1, 1 shape mid prediction, you will be fine.
